DEFAULT_DATABASE = 'default'
DEFAULT_USER = 'root'
DEFAULT_PASSWORD = ''
DEFAULT_SESSION_IDLE_TIME = 30
DEFAULT_CONNECT_TIMEOUT = 20
DEFAULT_READ_TIMEOUT = 20

DBMS_NAME = 'Databend'
CLIENT_NAME = 'databend-py'

STRINGS_ENCODING = 'utf-8'
